heat_template_version: 2018-08-31
description: "Composant Security Group - sous-template réutilisable"

parameters:
  sg_name:
    type: string
    default: heat-sg-custom
  description:
    type: string
    default: "Security group géré par Heat"

resources:
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { get_param: sg_name }
      description: { get_param: description }
      rules:
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: 0.0.0.0/0
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
          remote_ip_prefix: 0.0.0.0/0
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
          remote_ip_prefix: 0.0.0.0/0
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0

outputs:
  sg_id:
    description: ID du security group
    value: { get_resource: security_group }
  sg_name:
    description: Nom du security group
    value: { get_param: sg_name }
